### ISSUE TITLE
Code examples don't work with gradle 9.0.0

### ISSUE THREAD

**Issue by elijulian** [ben-manes/gradle-versions-plugin#959]
Hi, I'm trying to upgrade my gradle version to 9.0.0. I'm using the code suggestions that you have in the readme: 

```
tasks.withType<DependencyUpdatesTask> {
    resolutionStrategy {
        componentSelection {
            all {
                if (isNonStable(candidate.version) && !isNonStable(currentVersion)) {
                    reject("Release candidate")
                }
            }
        }
    }
}

```

I'm getting the following compilation errors:

```
./gradlew assemble

Welcome to Gradle 9.0.0!

Here are the highlights of this release:
 - Configuration Cache is the recommended execution mode
 - Gradle requires JVM 17 or higher to run
 - Build scripts use Kotlin 2.2 and Groovy 4.0
 - Improved Kotlin DSL script compilation avoidance

For more details see https://docs.gradle.org/9.0.0/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
e: file:///.../build.gradle.kts:259:33: Unresolved reference 'candidate'.
e: file:///.../build.gradle.kts:259:68: Unresolved reference 'currentVersion'.
e: file:///.../build.gradle.kts:260:21: Unresolved reference 'reject'.
```
